### ISSUE TITLE
trending tab doesnt work on 2.4.9.3

### ISSUE THREAD

**Issue by manoflinux** [pablouser1/TikScraperPHP#21]
ProxiTok-2.4.9.3/vendor/pablouser1/tikscraper/src/Signer.php on line 15
10.10.10.12:17184 [500]: GET /trending/rss - Uncaught TypeError: Cannot assign null to property TikScraper\Signer::$client of type TikScraper\Interfaces\SignerInterface in /home/sysop/ProxiTok-2.4.9.3/vendor/pablouser1/tikscraper/src/Signer.php:15
Stack trace:
#0 /home/sysop/ProxiTok-2.4.9.3/vendor/pablouser1/tikscraper/src/Sender.php(41): TikScraper\Signer->__construct()
#1 /home/sysop/ProxiTok-2.4.9.3/vendor/pablouser1/tikscraper/src/Api.php(17): TikScraper\Sender->__construct()
#2 /home/sysop/ProxiTok-2.4.9.3/app/Helpers/Wrappers.php(194): TikScraper\Api->__construct()
#3 /home/sysop/ProxiTok-2.4.9.3/app/Controllers/TrendingController.php(27): App\Helpers\Wrappers::api()
#4 [internal function]: App\Controllers\TrendingController::rss()
#5 /home/sysop/ProxiTok-2.4.9.3/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array()
#6 /home/sysop/ProxiTok-2.4.9.3/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke()
#7 /home/sysop/ProxiTok-2.4.9.3/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle()
#8 /home/sysop/ProxiTok-2.4.9.3/index.php(17): Bramus\Router\Router->run()
#9 {main}
  thrown in /home/sysop/ProxiTok-2.4.9.3/vendor/pablouser1/tikscraper/src/Signer.php on line 15

**Comment by manoflinux** [comment]
php 8.2 
Frontend version: 2.4.9.3

Scraper version: 2.4.0.0

**Comment by manoflinux** [comment]
expected behavior 
returns trending videos, instead gets 500 error and the above appears in the console.
